substitutions:
  voltage_divider: "1446.0976136351096"
  current_resistor: "0.0006145187444662681"
  current_multiply: "1.0"

esphome:
  name: smarthutplug
  friendly_name: Smart Hut Plug
  name_add_mac_suffix: true
  project:
    name: smarthut.esp32c3_plug
    version: "1.0.0"
  platformio_options:
    board_build.flash_mode: dio

dashboard_import:
  package_import_url: github://Smart-Hut/Smart-Plug/ESPC2-02.yaml@v1.2.1
  import_full_config: false # or true

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:

#Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart hut Plug"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO5
      inverted: true
    cf_pin: GPIO7
    cf1_pin: GPIO3
    voltage_divider: ${voltage_divider}
    current_resistor: ${current_resistor}
    current:
      name: "Current"
      filters:
        - multiply: ${current_multiply}
    voltage:
      name: "Voltage"
    power:
      name: "Power"
    energy:
      name: "Energy"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO20
      inverted: true
    name: button
    id: power_button
    on_press:
      then:
      - lambda: !lambda |-
          id(relay).toggle();

light:
  - platform: status_led
    id: wifi_light
    internal: true
    name: "Switch state"
    pin: 
      number: GPIO6
      inverted: true
  - platform: binary
    id: led
    name: "LED 2"
    output: gpio_led

output:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
    id: gpio_led

switch:
  - platform: gpio
    pin: GPIO4
    name: "plug"
    id: relay
    on_turn_on:
      then:
      - light.turn_on: wifi_light
    on_turn_off:
      then:
      - light.turn_off: wifi_light

button:
  - platform: restart
    name: Restart
  - platform: factory_reset
    name: Restart with Factory Default Settings