substitutions:
  voltage_divider: "787.8088303846923"
  current_resistor: "0.0009130339764619374"
  current_multiply: "0.41146559390160453"

esphome:
  name: smarthutplug
  friendly_name: Smart Hut Plug
  name_add_mac_suffix: true
  project:
    name: smarthut.esp32c3_plug
    version: "1.0.0"

dashboard_import:
  package_import_url: github://Smart-Hut/Smart-Plug/ESPC2-02.yaml@v1.2.1
  import_full_config: false # or true

esp32:
  board: esp32dev
  flash_size: 2MB
  variant: esp32c3


# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smart hut Plug"

captive_portal:

web_server:
  port: 80

sensor:
  - platform: hlw8012
    model: BL0937
    sel_pin: GPIO5
    cf_pin: GPIO7
    cf1_pin: GPIO3
    voltage_divider: ${voltage_divider}
    current_resistor: ${current_resistor}
    current:
      name: "Current"
      filters:
        - multiply: ${current_multiply}
    voltage:
      name: "Voltage"
    power:
      name: "Power"
    energy:
      name: "Energy"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO20
      inverted: true
    name: button
    id: button
    on_press:
      then:
      - lambda: !lambda |-
          id(relay).toggle();

light:
  - platform: status_led
    id: wifi_light
    internal: true
    name: "Switch state"
    pin: 
      number: GPIO6
      inverted: true

switch:
  - platform: gpio
    pin: GPIO4
    name: "plug"
    id: relay
    on_turn_on:
      then:
      - light.turn_on: wifi_light
    on_turn_off:
      then:
      - light.turn_off: wifi_light
